// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dosajii/AdminPanel.tsx": () => import("../components/mockups/dosajii/AdminPanel.tsx"),
  "./components/mockups/dosajii/CartCheckout.tsx": () => import("../components/mockups/dosajii/CartCheckout.tsx"),
  "./components/mockups/dosajii/Home.tsx": () => import("../components/mockups/dosajii/Home.tsx"),
  "./components/mockups/dosajii/Menu.tsx": () => import("../components/mockups/dosajii/Menu.tsx"),
  "./components/mockups/dosajii/ShopkeeperDashboard.tsx": () => import("../components/mockups/dosajii/ShopkeeperDashboard.tsx")
};
